# local dev compose (db only)
version: "3.8"
name: "ytaudio_dev"
services:
  postgres:
    image: postgres:15-alpine
    container_name: db_pg_dev
    env_file: ./api/config/.env
    volumes:
      - pg_data_vol:/var/lib/postgresql/data
    ports:
      - ${DJANGO_DATABASE_PORT:-5432}:5432
#    command: -p 5433
    networks:
      - net-dev
  front:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
      target: dev
    image: app/app_front_dev
    ports:
      - "8080:8080"
    volumes:
      - ./frontend:/app
    networks:
      - net-dev
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - net-dev
volumes:
  pg_data_vol: { }

networks:
  net-dev:
    driver: bridge
