# Generated by Django 4.2.1 on 2023-05-22 18:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import server.apps.video_tasks.models.video_source


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=255)),
                ('added_date', models.DateTimeField(auto_now_add=True)),
                ('source_id', models.CharField(blank=True)),
                ('extractor', models.CharField(blank=True, max_length=50)),
                ('title', models.CharField(blank=True)),
                ('channel', models.CharField(blank=True)),
                ('uploader_id', models.CharField(blank=True)),
                ('duration', models.PositiveSmallIntegerField(default=0)),
                ('upload_date', models.DateField(default='1900-01-01')),
                ('thumbnail', models.URLField(blank=True, max_length=255)),
                ('info', models.JSONField(default=dict)),
                ('file', models.FileField(max_length=255, null=True, upload_to=server.apps.video_tasks.models.video_source.upload_directory_path)),
                ('file_size', models.IntegerField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-added_date'],
            },
        ),
        migrations.AddConstraint(
            model_name='videosource',
            constraint=models.UniqueConstraint(condition=models.Q(('title', ''), _negated=True), fields=('source_id', 'extractor'), name='unique_source_id_extractor'),
        ),
    ]
