# Generated by Django 4.2 on 2023-04-06 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='videosource',
            name='url',
            field=models.URLField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
