# Generated by Django 4.2.1 on 2023-05-22 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videosource',
            name='url',
            field=models.URLField(max_length=255, unique=True),
        ),
    ]
