# Generated by Django 4.2.1 on 2023-05-14 12:15

from django.db import migrations, models
import server.apps.video_tasks.models.video_source


class Migration(migrations.Migration):

    dependencies = [
        ('video_tasks', '0002_videosource_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='videosource',
            name='channel',
            field=models.CharField(blank=True),
        ),
        migrations.AddField(
            model_name='videosource',
            name='duration',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='videosource',
            name='extractor',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='videosource',
            name='file',
            field=models.FileField(max_length=255, null=True, upload_to=server.apps.video_tasks.models.video_source.upload_directory_path),
        ),
        migrations.AddField(
            model_name='videosource',
            name='file_size',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='videosource',
            name='info',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='videosource',
            name='source_id',
            field=models.CharField(blank=True),
        ),
        migrations.AddField(
            model_name='videosource',
            name='thumbnail',
            field=models.URLField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='videosource',
            name='title',
            field=models.CharField(blank=True),
        ),
        migrations.AddField(
            model_name='videosource',
            name='upload_date',
            field=models.DateField(default='1900-01-01'),
        ),
        migrations.AddConstraint(
            model_name='videosource',
            constraint=models.UniqueConstraint(condition=models.Q(('title', ''), _negated=True), fields=('source_id', 'extractor'), name='unique_source_id_extractor'),
        ),
    ]
